SOURCES=main.cpp \
	camera/camera.cpp \
	scene/scene.cpp \
	extra/polygon.cpp \
	extra/utility.cpp \
	extra/kdtree.cpp \
	light/light.cpp \
	obj_parser/material.cpp \
	obj_parser/material_lib.cpp \
	obj_parser/obj_loader.cpp \
	obj_parser/object.cpp 

OBJS=$(patsubst %.cpp, _build/%.o, $(SOURCES))
